from dotenv import load_dotenv
import os

load_dotenv()
BINGNAME = os.getenv("BING_NAME")
BINGPASS = os.getenv("BING_PASSWORD")
BINGUSER = os.getenv("BING_USERNAME")
CHATGPT = os.getenv("CHATGPT_KEY")
CONSUMERAPI = os.getenv("TWITTER_CONSUMER_API")
CONSUMERSECRET = os.getenv("TWITTER_CONSUMER_SECRET")
STABILITY = os.getenv("STABILITY_KEY")
TWITTERACCESS = os.getenv("TWITTER_ACCESS_KEY")
TWITTERBEARER = os.getenv("TWITTER_BEARER_KEY")
TWITTERSECRET = os.getenv("TWITTER_SECRET_KEY")